version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # 设置数据库密码
      - MYSQL_DATABASE=your_database_name # 初始化数据库名称
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  app:
    build:
      context: /Users/zj008/eladmin # Dockerfile 所在目录
      dockerfile: Dockerfile # 如果你需要自定义 Dockerfile
    container_name: eladmin
    volumes:
      - /Users/zj008/eladmin:/home/eladmin # 挂载本地代码目录
    ports:
      - "8080:8000"
    environment:
      - TZ=Asia/Shanghai
      - DB_HOST=db
      - DB_PWD=123456
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always

  node:
    image: node:14 # 使用符合要求的 Node.js 版本
    container_name: eladmin-node
    volumes:
      - /Users/zj008/eladmin-web:/home/eladmin-web # 挂载前端代码目录
    working_dir: /home/eladmin-web
#    command: sh -c "npm install && npm run build" # 执行构建命令
    command: sh -c "npm install && npm run build:prod" # 使用 build:prod

    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/zj008/eladmin/nginx/nginx.conf:/etc/nginx/nginx.conf # 挂载本地的 nginx.conf
      - /Users/zj008/eladmin/nginx/conf.d:/etc/nginx/conf.d # 挂载本地 conf.d 目录
      - /Users/zj008/eladmin/nginx/logs:/var/log/nginx # 挂载本地日志目录
      - /Users/zj008/eladmin/nginx/cert:/etc/nginx/cert # 挂载本地证书目录
      - /Users/zj008/eladmin-web/dist:/usr/share/nginx/html/eladmin/dist # 挂载前端构建的静态文件
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - app
      - node
    restart: always

volumes:
  db_data:
  redis_data:
