version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=eladmin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure

  app:
    build:
      context: K:/eladmin
      dockerfile: Dockerfile
    container_name: eladmin
    volumes:
      - K:/eladmin:/home/eladmin
#      - ~/.m2:/root/.m2
    ports:
      - "8080:8000"
    environment:
      - TZ=Asia/Shanghai
      - DB_HOST=db
      - DB_PWD=123456
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: on-failure
    command: mvn clean package

  node:
    image: node:14
    container_name: eladmin-node
    volumes:
      - K:/eladmin-web:/home/eladmin-web
      - /home/eladmin-web/node_modules:/home/eladmin-web/node_modules
    working_dir: /home/eladmin-web
    command: sh -c "npm install && npm run build:prod"
    restart: on-failure
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - K:/eladmin/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - K:/eladmin/nginx/conf.d/eladmin.conf:/etc/nginx/conf.d/eladmin.conf:ro
      - K:/eladmin/nginx/logs:/var/log/nginx
      - K:/eladmin/nginx/cert:/etc/nginx/cert
      - K:/eladmin/nginx/dist:/usr/share/nginx/html/eladmin/dist:ro
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - app
      - node
    command: /bin/sh -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: on-failure

volumes:
  db_data:
  redis_data:
