version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # 设置数据库密码
      - MYSQL_DATABASE=your_database_name # 初始化数据库名称
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  app:
    build:
      context: K:/eladmin # Dockerfile 所在目录
      dockerfile: Dockerfile
    container_name: eladmin
    volumes:
      - K:/eladmin:/home/eladmin # 挂载本地代码目录
    ports:
      - "8080:8000" # 修改：确保容器内使用 8000 端口暴露服务，外部映射为 8080
    environment:
      - TZ=Asia/Shanghai
      - DB_HOST=db
      - DB_PWD=123456
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always

  node:
    image: node:14 # 使用符合要求的 Node.js 版本
    container_name: eladmin-node
    volumes:
      - K:/eladmin-web:/home/eladmin-web # 挂载前端代码目录
    working_dir: /home/eladmin-web
    command: sh -c "npm install && npm run build:prod" # 使用 build:prod 构建前端
    restart: always
    # 修改建议：增加 depends_on 以确保数据库和 Redis 服务就绪后再启动
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - K:/eladmin/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # 确保配置文件只读挂载
      - K:/eladmin/nginx/conf.d/eladmin.conf:/etc/nginx/conf.d/eladmin.conf:ro
      - K:/eladmin/nginx/logs:/var/log/nginx
      - K:/eladmin/nginx/cert:/etc/nginx/cert
      - K:/eladmin/nginx/dist:/usr/share/nginx/html/eladmin/dist:ro # 挂载前端静态文件为只读
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - app
      - node
    command: /bin/sh -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" # 删除默认配置并前台启动
    restart: always

volumes:
  db_data:
  redis_data: